USE supertour;

INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('1', 'Trevion', 'Champlin', 'Steuber', 'bernardo97@example.net', '9165764435', '530 Conroy Trail\nEdisonburgh, ME 49947', '57585079.17057');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('2', 'Tara', 'Greenholt', 'Schiller', 'prath@example.net', '9092989617', '6443 Elliot Isle Suite 994\nEast Shayleechester, NE 83204-9199', '36063387.368835');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('3', 'Hoyt', 'Schulist', 'Christiansen', 'rolfson.linnie@example.org', '9062142722', '26564 Bahringer Manor Suite 156\nDantefort, MO 14536-0354', '85109198.64993');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('4', 'Javon', 'Legros', 'Beatty', 'albertha.murray@example.net', '9344069530', '0576 Goodwin Garden\nD\'angelochester, OR 40620', '88837199.843878');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('5', 'Dena', 'Gerlach', 'Kris', 'grant.breanna@example.org', '9806351345', '5747 Franecki Ferry Suite 824\nCristobalburgh, AR 37352', '34207587.03');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('6', 'Vivian', 'Wuckert', 'Boyle', 'malvina36@example.org', '9974252098', '8356 Haley Stream\nAileenport, AR 58264', '39279330');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('7', 'Corrine', 'McGlynn', 'Bins', 'ayana12@example.org', '9836529722', '028 Lynch Shore\nNorth Jarodton, MA 49643-6313', '87278485.78');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('8', 'Gene', 'Dibbert', 'Turner', 'veum.myra@example.org', '9913234372', '7917 Lueilwitz Mountain\nNew Rodrigoville, LA 86240-5438', '61593942.44');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('9', 'Lucienne', 'Krajcik', 'Cruickshank', 'jaclyn46@example.com', '9377382178', '82908 Schuster Crossroad\nDarrenshire, MT 69451', '36852438.909');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('10', 'Torey', 'Steuber', 'Schuster', 'ckuhn@example.net', '9435649146', '489 Jesus Cove\nWest Ena, AR 64505-5369', '59997681.663371');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('11', 'Jake', 'Emmerich', 'Funk', 'purdy.ocie@example.org', '9448384418', '59246 Adams Lodge\nAbigalehaven, GA 52030', '72004249.683583');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('12', 'Aracely', 'Wilkinson', 'Jacobson', 'jacobs.allen@example.net', '9341242524', '6465 Zetta Corner\nMeggietown, WY 83264-8447', '75802427.225654');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('13', 'Cassidy', 'Abbott', 'Doyle', 'natalia.wyman@example.org', '9920337204', '0465 Brandt Spurs Apt. 049\nImmanuelfort, NJ 02288', '13470758.909113');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('14', 'Ashly', 'Block', 'Stoltenberg', 'ywest@example.com', '9669274616', '86384 Prudence Ridges\nPort Seanview, OR 65411-5942', '27954753.533916');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('15', 'Benton', 'Dibbert', 'McGlynn', 'bartoletti.petra@example.net', '9677301727', '1009 Westley Rapid Suite 510\nLaurettaport, OR 84279-4017', '69627703.679552');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('16', 'Jed', 'Rice', 'Rohan', 'mhoeger@example.com', '9346364707', '5041 Gutkowski Forges\nCreolafort, VA 28192-2402', '86280042.7');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('17', 'Karli', 'Stehr', 'Davis', 'madaline.boehm@example.com', '9579369115', '025 Mohr Field Apt. 673\nAliciaberg, NV 65503', '46524150.165042');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('18', 'Keenan', 'O\'Keefe', 'Mayert', 'ywisoky@example.org', '9373492552', '4683 Lennie Walk Apt. 084\nDevanport, NC 85154-3210', '61259440.580038');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('19', 'Jany', 'Bruen', 'Kovacek', 'cummerata.una@example.net', '9929244610', '4971 Beer Roads Suite 606\nKozeybury, PA 33677-2420', '25880031.816606');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('20', 'Gus', 'Spinka', 'Kling', 'kyost@example.net', '9046710149', '1706 Daugherty Forks\nSouth Arden, RI 91841', '86782692.3713');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('21', 'Reese', 'Gerlach', 'Littel', 'hadley.hammes@example.com', '9247531780', '495 Alberta Trail\nEthaborough, WY 55169', '47282345');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('22', 'Gunner', 'Kassulke', 'Kunde', 'steve.ratke@example.org', '9037529943', '979 Pauline Overpass Suite 132\nWest Scottieborough, NV 43893-3898', '20631310.162428');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('23', 'Abby', 'Macejkovic', 'Jakubowski', 'schroeder.forrest@example.org', '9998673731', '3353 Lebsack Junctions\nAthenaview, MS 74053', '84461903.047963');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('24', 'Darrin', 'Ritchie', 'Schultz', 'fidel93@example.net', '9056051353', '8670 Ceasar Turnpike\nSouth Holdenfort, MI 41853', '15247180.836856');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('25', 'Fritz', 'Turner', 'Wunsch', 'bmurazik@example.org', '9030787162', '46735 Nathanael Lock Suite 058\nEast Beverly, WV 31325', '46978713.328475');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('26', 'Leonel', 'Langworth', 'Bogan', 'pouros.kaylah@example.com', '9205270439', '3539 Terry Center\nConniefort, MA 35602', '54386576');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('27', 'Jess', 'Rodriguez', 'Davis', 'bsawayn@example.org', '9136989923', '960 Blick Mall\nEast Tomasamouth, ND 07616', '79044147.53851');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('28', 'Zackary', 'Stiedemann', 'Heathcote', 'zackary.gislason@example.net', '9936651029', '5404 VonRueden Ranch Suite 910\nThielton, NY 98512', '42233196.288456');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('29', 'Ardith', 'McKenzie', 'Hickle', 'kassulke.maddison@example.org', '9045106295', '672 Brian Wells\nBillview, TX 70255', '40933048');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('30', 'Colin', 'Mante', 'Sporer', 'xo\'connell@example.org', '9669881169', '742 Jane Mission\nNorth Anna, MT 68029-2894', '82986696.21022');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('31', 'Chadd', 'Emmerich', 'Champlin', 'fbashirian@example.net', '9380719215', '727 Raheem Fields Suite 169\nO\'Konhaven, IL 90154', '86977594');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('32', 'Brooks', 'Simonis', 'Koepp', 'lamar79@example.org', '9712693005', '74156 Boyer Circles\nJordanville, TX 58074', '54922089.11335');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('33', 'Aurelia', 'Stiedemann', 'Kovacek', 'heidenreich.tyrese@example.net', '9899695826', '0098 Beahan Avenue\nNorth Carroll, KS 40925-4455', '83920605.22');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('34', 'Liana', 'Rippin', 'Keeling', 'jborer@example.com', '9266074047', '333 Judy Crest\nKesslerhaven, NC 74881', '32774482.603546');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('35', 'Walton', 'Miller', 'Sanford', 'freddy16@example.net', '9526967837', '669 Crooks Coves\nSchimmelmouth, CT 84648', '66552916.6798');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('36', 'Alan', 'Murazik', 'Leuschke', 'eortiz@example.net', '9645058977', '57288 Wehner Expressway\nNorth Rosellaton, MN 92259-1322', '50317427.94454');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('37', 'Adrianna', 'Jaskolski', 'Erdman', 'grady.kuhn@example.net', '9381840131', '022 Leora Fork\nSouth Martaton, IN 11953-6180', '50163110.6');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('38', 'Deron', 'Ward', 'Stokes', 'sporer.josefina@example.net', '9145413346', '596 Eichmann Roads\nEast Magdalena, WI 80673-1539', '69849762.795423');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('39', 'Eudora', 'Von', 'Bosco', 'susie65@example.com', '9604697036', '370 Wilkinson Club\nAnibalhaven, MA 02646-6035', '36353131.0234');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('40', 'Carmel', 'Wilderman', 'Thiel', 'franecki.kelton@example.com', '9454442570', '86327 Shayna Vista Apt. 549\nSouth Nat, NV 95351', '73758043');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('41', 'Elmer', 'Nicolas', 'Schuster', 'zdooley@example.org', '9614808856', '5120 Jamil Course\nGerlachland, VT 68834', '85944763.2');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('42', 'Kailee', 'Farrell', 'Gislason', 'jude.trantow@example.net', '9494536518', '43168 Vladimir Extensions Apt. 084\nNew Yasmine, SD 26923-3673', '24531240.693541');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('43', 'Quinten', 'Cronin', 'Johnston', 'ernser.johnny@example.org', '9718673690', '298 Kihn Fields Suite 445\nPort Dedricmouth, AR 29415', '88891913.4');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('44', 'Paula', 'Larkin', 'Huel', 'reyna51@example.com', '9187864735', '51266 Krista Street Apt. 934\nSouth Giovanni, ID 89809-1879', '40883938.6');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('45', 'Theresia', 'Durgan', 'Fay', 'jkoss@example.com', '9393989794', '238 Corbin Cliff Apt. 350\nWest Lourdes, NH 38091-8594', '40995877.958367');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('46', 'Haven', 'Schuppe', 'Kirlin', 'ernest88@example.com', '9668818396', '041 Alvena Junction Suite 706\nPricefurt, KS 05058-0110', '72456320.44154');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('47', 'Cassandra', 'Brekke', 'Schamberger', 'torrance19@example.net', '9386806225', '016 Bessie Plains\nAureliomouth, ND 15161-2020', '10870489.031482');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('48', 'Stephania', 'Wiegand', 'Wolf', 'rosenbaum.guiseppe@example.net', '9362867484', '8440 Breitenberg Ville\nAdeliachester, CA 58065', '76075476.699544');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('49', 'Katlynn', 'Dibbert', 'Anderson', 'trantow.margarete@example.net', '9389758921', '737 Heaney Plains Suite 820\nJanaeborough, DE 66245-0644', '37036250.80503');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('50', 'Emie', 'Wisozk', 'Rempel', 'vladimir.hahn@example.org', '9104987546', '16091 Gerhold Court\nSouth Hester, NV 66813', '24818338.535176');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('51', 'Jonas', 'Grady', 'Haag', 'wisoky.adele@example.com', '9396036499', '8929 Wintheiser Isle\nSouth Eldoramouth, VT 22303-8073', '25228791.24');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('52', 'Leonard', 'Nikolaus', 'Kulas', 'rozella71@example.org', '9900102571', '736 Isidro Pike\nNew Junius, DC 26808', '13075354.435982');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('53', 'Randal', 'Franecki', 'Koss', 'kautzer.tremaine@example.org', '9008989172', '462 Rowland Garden Suite 431\nPort Antonia, MA 87284-6864', '22686929.671414');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('54', 'Richmond', 'Moen', 'Bechtelar', 'jarrett.mayer@example.com', '9517684231', '45522 Wendell Wall\nMohammadchester, MI 49225', '31463716.598909');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('55', 'Magnolia', 'Murazik', 'Schumm', 'ettie.hills@example.org', '9446955385', '504 Rebekah Mills Suite 783\nSouth Ludwig, NY 70232', '88784123.062521');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('56', 'Vincenza', 'Rau', 'Cremin', 'sweber@example.net', '9449832513', '95657 Angeline Square\nErdmanfort, IL 27243-1713', '26035621.099191');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('57', 'Hayden', 'Daniel', 'Kuhn', 'curt.quitzon@example.com', '9098443213', '691 Edythe Shores Apt. 186\nCheyenneville, HI 08340', '10636488.7956');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('58', 'Jasen', 'O\'Conner', 'Ward', 'cyrus09@example.org', '9296200372', '7853 O\'Hara Inlet\nPort Jaquelineton, WI 27552-5190', '86296391.4');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('59', 'Jannie', 'O\'Kon', 'Hoeger', 'rwunsch@example.com', '9275375785', '4802 Raphaelle Ridges\nQuigleyhaven, OK 77514-4218', '59422044');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('60', 'Julianne', 'Stoltenberg', 'McLaughlin', 'willard.cummerata@example.net', '9115259710', '84644 Nellie Corner\nSouth Lizzie, SD 02960-5805', '53513918.54');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('61', 'Kurt', 'Oberbrunner', 'Hilll', 'batz.earnest@example.com', '9185612210', '96385 Hoppe Trafficway Apt. 924\nQuintenburgh, TN 74341', '11060886.458056');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('62', 'Jeanie', 'Quigley', 'Rath', 'aida.ernser@example.org', '9841176244', '5473 Barry Stream Apt. 354\nRainaborough, SC 95093-8857', '58875744.924357');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('63', 'Bernita', 'Dicki', 'Stroman', 'dkoepp@example.net', '9014265281', '53362 Grant Villages Apt. 744\nBrookemouth, RI 61191', '25537068.2');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('64', 'Cary', 'Muller', 'Boehm', 'rowe.elody@example.org', '9116466360', '76207 Langosh Gardens\nWest Brendaburgh, HI 64906-8393', '40647956.557');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('65', 'Darren', 'Walker', 'Hickle', 'sabina63@example.com', '9497629636', '075 Brianne Dale Suite 603\nConnellychester, MS 97857', '40899781.525');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('66', 'Sibyl', 'Pfannerstill', 'Lehner', 'kozey.candida@example.com', '9056044874', '5331 Gottlieb Pike Suite 033\nZiemeton, SC 41709', '71107816.091323');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('67', 'Scot', 'Hermann', 'Kovacek', 'goyette.lavern@example.net', '9168927301', '4082 Mayert Cove Apt. 095\nWest Dannie, ME 54517-5473', '30344270.141956');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('68', 'Don', 'Jones', 'Von', 'lenora01@example.net', '9485781273', '61603 Maggie Drive Apt. 760\nLuthertown, AK 34917-0137', '59176389.039111');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('69', 'Daniela', 'Doyle', 'Pollich', 'tmedhurst@example.org', '9790661729', '913 Kira Court Suite 584\nSouth Owen, NH 36902', '14676739.501');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('70', 'Sincere', 'Beahan', 'Thompson', 'margret.huels@example.org', '9559804632', '50965 Bechtelar Inlet\nPort Matteo, WI 78424', '23916380.74718');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('71', 'Haley', 'Leuschke', 'Gusikowski', 'bechtelar.vita@example.com', '9143204812', '729 Zboncak Estate\nHaneview, GA 44592', '18980353.851328');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('72', 'Flavio', 'Thompson', 'Senger', 'tillman.graham@example.net', '9283055108', '1863 Kessler Summit\nPort Haleyport, ID 60973-1793', '52689138.559014');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('73', 'Katelynn', 'Johnston', 'Quigley', 'nova68@example.org', '9723753359', '273 O\'Keefe Valley\nNew Lionelton, SC 87997-7101', '28775090.84');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('74', 'Lyla', 'Cummings', 'Hermann', 'fhuels@example.com', '9503318460', '2346 Michale Turnpike Suite 405\nSouth Pierce, WA 79050-6417', '87692276.872');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('75', 'Janiya', 'Grant', 'Koepp', 'vicente83@example.org', '9231701550', '1892 Anthony Run\nLake Elsafurt, MA 03259', '45878021.174985');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('76', 'Elouise', 'Hand', 'Schulist', 'blick.ivory@example.net', '9410658675', '8313 Gerlach Shoals Suite 791\nHeathcoteton, WI 76210', '47375329.675793');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('77', 'Leda', 'Wisozk', 'Sanford', 'johnson.helene@example.com', '9146514359', '28207 Ortiz Mount\nNew Meda, MT 85382', '35165348.288');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('78', 'Augustine', 'O\'Kon', 'Bergnaum', 'leilani.mayer@example.org', '9256459396', '306 Cristopher Shoals Apt. 332\nLake Reyes, MT 18526-0081', '72855336.769882');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('79', 'Cassie', 'Braun', 'Murphy', 'ari52@example.net', '9708826293', '04877 Von Flat Suite 310\nMarquardtborough, NM 74412', '77274087.8');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('80', 'Karina', 'Reilly', 'Runolfsson', 'lmclaughlin@example.org', '9627160858', '467 Libbie Common\nSouth Jayden, RI 65287', '81106371.9499');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('81', 'Breanne', 'Daugherty', 'Jacobs', 'ljaskolski@example.org', '9288495594', '3315 Teresa Center Suite 970\nTorrancemouth, SC 17499-8131', '41452399');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('82', 'Adan', 'Schaden', 'Will', 'trevion.adams@example.org', '9295133268', '279 Balistreri Islands\nWest Maxwell, CO 32807-0446', '82412890.937372');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('83', 'Toby', 'Runolfsdottir', 'Leannon', 'pschiller@example.net', '9576028370', '878 Roob Station Suite 429\nVonhaven, OH 66954-2271', '18310220.692');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('84', 'Al', 'Pfannerstill', 'Schuster', 'paucek.connor@example.org', '9248673899', '27756 Mante Stravenue Suite 707\nCrystelburgh, NM 79148-3768', '75596427.76');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('85', 'Wilmer', 'Goldner', 'Kozey', 'kraig44@example.org', '9151561773', '26009 Sidney Way Suite 192\nCartwrighttown, HI 35258', '81037696.484028');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('86', 'Bo', 'McClure', 'Jones', 'howe.delores@example.com', '9334625180', '6501 Block Corners\nRubyeside, NJ 18745-1360', '22914771');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('87', 'Icie', 'Ledner', 'Johns', 'zkoelpin@example.com', '9013421705', '857 Nitzsche Trace Suite 543\nYoststad, MT 79142', '18113681.864');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('88', 'Brian', 'Adams', 'Ryan', 'hlarson@example.org', '9782581046', '801 Brad Pike Suite 807\nHandshire, MA 91954-8811', '71013355');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('89', 'Nedra', 'Nikolaus', 'Jacobson', 'skuvalis@example.org', '9036560425', '455 Goyette Via Suite 585\nJuanaland, OH 74805-8134', '81228938.9');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('90', 'Max', 'Marquardt', 'Hoppe', 'bechtelar.justine@example.net', '9903542633', '9232 Leonie Mountains\nWest Mike, NC 30478', '70181654.347191');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('91', 'Bradly', 'Doyle', 'Gleichner', 'savannah19@example.org', '9724256217', '847 Nitzsche Pass\nSigmundbury, NV 73411', '16158242.41');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('92', 'Lillie', 'Mitchell', 'Reichel', 'eschumm@example.org', '9095442199', '05119 Kris Rapids Apt. 606\nRudyport, CO 28059', '46386791.86');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('93', 'Maynard', 'Stoltenberg', 'Rippin', 'muhammad80@example.com', '9379546090', '909 Claudie Stream Suite 380\nSouth Dixie, TX 98927', '75562616.766227');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('94', 'Percival', 'Larkin', 'Kris', 'antwon98@example.net', '9193143356', '58369 Jules Plain Apt. 763\nDejahaven, MT 14763', '65214726.019285');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('95', 'Kellen', 'Kreiger', 'Rippin', 'tschinner@example.org', '9152026855', '653 Dicki Parks Apt. 467\nPort Darbyfurt, HI 22654-4310', '89362473.82283');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('96', 'Elisha', 'Nikolaus', 'Ruecker', 'casey.brown@example.com', '9147223507', '3653 Klocko Circles Apt. 189\nNorth Ambroseborough, CA 06846-0540', '12138761.282963');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('97', 'Rosalind', 'McLaughlin', 'Wiza', 'corine81@example.com', '9575133015', '575 Napoleon Glen Suite 177\nEast Elenoramouth, OK 91604', '62576079.39307');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('98', 'Clementina', 'Romaguera', 'Bradtke', 'ariel21@example.com', '9613104364', '6529 Wolff Forge\nNew Kiarra, NM 20758-4532', '12582950.29522');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('99', 'Avis', 'Wiza', 'Wiegand', 'israel.bradtke@example.com', '9716071036', '541 Sipes Burg\nNorth Angeline, DC 60759', '20691423');
INSERT INTO `clients` (`id`, `firstname`, `lastname`, `middle_name`, `email`, `phone`, `address`, `passport`) VALUES ('100', 'Dasia', 'Hand', 'Goodwin', 'cwehner@example.net', '9926197060', '9749 Stella Valley\nSouth Santiago, WA 03609-0537', '75084991.634397');

INSERT INTO countries (name) VALUES
	('Russia'),
	('Italy'),
	('Poland'),
	('Finland'),
	('Turkey'),
	('Sweden'),
	('Egypt'),
	('Canada'),
	('China'),
	('Japan');

INSERT INTO cities (name, countries_id, description) VALUES
	('Moscow', 1, ' Город стоит на Москве-реке в Центральной России, его население оценивается в 12,4 миллиона жителей в черте города, более 17 миллионов жителей в городской черте и более 20 миллионов жителей в столичном регионе.'),
	('Saint-Petersburg', 1, 'Город на Неве, самый лучший город'),
	('Stockholm', 6, ' столица и крупнейший город Швеции. Расположен на протоках, соединяющих озеро Меларен с Балтийским морем.'),
	('Rome', 2, ' столица и крупнейший город Италии (по населению агломерации уступает Милану и Неаполю).'),
	('Sharm el-sheikh', 7, 'город-курорт в Египте на южной оконечности Синайского полуострова на побережье Красного моря Египетской ривьеры.'),
	('Hurghada', 7, ' город на востоке Египта, расположен в Африканской части Египта. Расположен на западном побережье Красного моря, на 400 км юго-восточнее Каира.'),
	('Venice', 2, 'Венеция и одноимённой территориальной единицы, приравненной к провинции.'),
	('Antalia', 5, 'Анталия стала центром санджака – административной единицы Османской империи.'),
	('Pekin', 9, 'Пеки́н — столица и один из городов центрального подчинения Китайской Народной Республики. Пекин с трёх сторон окружён провинцией Хэбэй и граничит с Тяньцзинем на юго-востоке.'),
	('Ottawa', 8, 'Расположена в восточной части провинции Онтарио на берегу реки Оттавы, по которой проходит граница между провинциями Онтарио и Квебек.'),
	('Warsaw', 3, 'столица и крупнейший по населению и по территории город Польши. Город стал фактической столицей в 1596 году.');


INSERT INTO currencies VALUES
	(1, 'RUR', 'рубль', 1),
	(2, 'USD', 'доллар', 58.1),
	(3, 'EUR', 'евро', 56.48),
	(4, 'GBR', 'фунт_стерлингов', 65.45),
	(5, 'JPY', 'йена', 0.4022);
	
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('1', 'Parisian, Wilkinson and Kuhlman', '9', '8', '8240 Grayson Ports\nNorth Leolamouth, MA 66375', '4', 'Enim nobis accusamus molestias ratione temporibus voluptas culpa. Corporis qui et assumenda qui aliquam inventore. Et laboriosam ducimus rerum atque sit et provident. Molestiae aspernatur occaecati sapiente eligendi omnis natus et.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('2', 'Wilderman-Farrell', '4', '11', '4665 Lueilwitz Meadows\nLake Nelle, TX 32063', '1', 'Molestiae iure et tempore est. At et totam explicabo molestias delectus consequatur. A voluptatem ut et totam est voluptatem molestias. Aut aut est rerum aut ullam nesciunt dolor.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('3', 'Howe Ltd', '3', '3', '555 Nolan Island Apt. 369\nTremainestad, MN 61169', '4', 'Magni rem pariatur quae ab eos. Maiores eveniet voluptatum adipisci est in sequi voluptatem. Et voluptas beatae deleniti rem laudantium et. Dolor in voluptatum eius accusantium eos vel inventore praesentium.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('4', 'Johnson-Cormier', '1', '11', '52899 Immanuel Ville Suite 076\nCormierfurt, WV 71410-9740', '1', 'Rem dolore dignissimos dolorem voluptatibus. Asperiores sequi autem eveniet vitae et error culpa. Et eius autem quidem ea assumenda corporis. Velit rerum ut corrupti.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('5', 'Goodwin LLC', '10', '7', '28571 Fritz Village\nSouth Orlandview, AL 59177', '4', 'Sed molestiae sit qui omnis eaque et pariatur. Quod tempore laboriosam ut voluptatum et labore consequatur non. Sit dolor et deserunt illo sed deleniti eum.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('6', 'Block-Kreiger', '5', '10', '5431 Schmeler Corners Apt. 939\nNew Rosalind, NJ 20815-0083', '2', 'Voluptas mollitia et voluptatem nemo. Nisi itaque sit est.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('7', 'Jaskolski, Wolf and Parker', '7', '8', '6896 Sanford Fall\nStromanview, OH 83858-4500', '1', 'Voluptatibus inventore suscipit sit doloribus ut dolor voluptas. Inventore nobis quae non debitis. Ducimus nisi qui officiis accusantium.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('8', 'Jenkins LLC', '5', '4', '268 O\'Connell Parks Apt. 325\nPort Raoulborough, VA 63985-6134', '2', 'Dolorum quaerat assumenda sequi delectus sit. Quia odio possimus reiciendis ipsam atque accusamus architecto. Debitis iste minus est vel.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('9', 'Mayer PLC', '5', '3', '2893 Wiza Glen Apt. 791\nNew Haven, MO 64567', '3', 'Laudantium quae ea error adipisci qui non deserunt cupiditate. Ut eaque ex excepturi qui. Est aut enim aspernatur possimus deserunt et illo. Aliquam sint iusto eos. Omnis est dolorem molestias quam dolor.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('10', 'Padberg, Macejkovic and Vandervort', '8', '6', '90995 Beier Drive\nWest Laurinemouth, VT 97372-8043', '1', 'Ipsam dignissimos officia modi expedita officia illum. Mollitia molestiae aut consequatur nemo similique. Sint voluptas ea facilis odio tempore.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('11', 'Lesch-Wisoky', '9', '3', '9576 Prohaska Coves Apt. 424\nArtville, DE 92198-9395', '2', 'Dolores reprehenderit minima in saepe et. Nostrum inventore facere sed quis eius. Nemo id delectus ratione distinctio excepturi esse corrupti accusamus.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('12', 'Jones, Pollich and Turcotte', '10', '1', '1248 Lucio Dale Apt. 141\nSouth Liaberg, WI 80116-5852', '2', 'Necessitatibus nostrum deserunt et rem. Minima dolorum magnam inventore sed. Quia sequi sit et cumque.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('13', 'O\'Keefe, Mraz and McGlynn', '2', '6', '437 Spencer Islands Suite 999\nDavefort, AR 28664', '3', 'Explicabo voluptatem perferendis repellat. Odio et et dolores aut fuga velit eos. Dicta itaque aut qui iusto necessitatibus. Sunt vel quod id dignissimos quo quia aspernatur.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('14', 'Toy-Hintz', '6', '4', '527 Kreiger Wall Suite 846\nNorth Elmer, AR 07974', '1', 'Adipisci tenetur consectetur omnis harum non laborum. Aut omnis dolores totam ut. Placeat unde eos et provident non optio non inventore.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('15', 'Lynch-Grady', '2', '10', '23761 Ratke Streets Suite 437\nCorbinview, MA 03229', '3', 'Rerum id omnis iste rerum in hic fugiat. Tempore delectus dolor esse tempora. Doloremque et eveniet rem ea provident quo ut. Quo sed nam dolorem soluta reiciendis.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('16', 'Parisian Group', '1', '4', '91963 Gusikowski Key Suite 337\nMosheton, WV 67963', '2', 'Similique aperiam nesciunt quibusdam illo repellat praesentium ipsa corrupti. Facere quidem sequi repudiandae autem. Molestiae beatae non tempore dignissimos consequatur dolorum.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('17', 'Bailey, O\'Keefe and Kris', '6', '5', '85436 Kreiger Gateway\nNorth Marcelino, NM 39149-5075', '3', 'A quia consequatur debitis assumenda placeat. Voluptas qui consequuntur eos molestiae laudantium saepe et. Asperiores saepe voluptatem ducimus earum facere. Quia id unde voluptatem vel animi dignissimos ratione.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('18', 'Stark LLC', '7', '4', '845 Delfina Light\nLake Arne, NM 61492-7978', '4', 'Nesciunt et accusantium minus. Recusandae iste labore cumque ipsam explicabo reprehenderit a. Dolorem eligendi sit laboriosam. Eos excepturi reprehenderit facilis autem ipsum possimus suscipit.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('19', 'Becker, Prohaska and Dach', '8', '5', '452 Chesley Bridge\nJessymouth, RI 80640-7278', '4', 'Aut nobis doloremque tempore ducimus. Ab non et blanditiis.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('20', 'Kunde and Sons', '9', '9', '143 Bernier Village Suite 285\nLake Gaylestad, KS 66100', '3', 'Nesciunt et tempore nobis adipisci veritatis. Architecto est error laboriosam. Autem laudantium eligendi facilis aliquam nihil labore.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('21', 'Johnson-Bernhard', '9', '8', '50176 Heller Summit\nJohnsonport, KS 63187', '3', 'Laborum aliquam culpa autem harum non. Omnis quia a velit enim. Similique consequatur qui ut doloribus minima.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('22', 'Watsica-Orn', '5', '3', '025 Crist Meadows Suite 611\nSouth Beaulahton, NH 75940-9923', '4', 'Mollitia enim nam est eligendi est et cumque nihil. Sit nam odit eaque omnis facilis et ut. Commodi temporibus voluptatem qui itaque. Minus debitis consequatur sunt voluptatibus libero.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('23', 'Brakus-Balistreri', '7', '3', '390 Donnelly Wall\nPort Ayden, OK 80460', '1', 'Dignissimos aut quasi qui nobis sequi. Et enim sit ut aut sequi sint est. Dolore vero mollitia aperiam error aut officia. Expedita itaque quisquam atque alias.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('24', 'Watsica, Okuneva and Ratke', '9', '8', '5217 Monserrat Neck Apt. 728\nGerholdberg, SC 95455-3104', '5', 'Illo omnis dolores corporis sed maxime. Quo ipsa deleniti officia vero velit. Iusto facere minus aspernatur sequi expedita quia ut ipsa.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('25', 'Sipes and Sons', '4', '6', '6011 Doyle Port Apt. 598\nClintonmouth, NC 54094-6986', '4', 'Non delectus et vitae aut quidem vel. Quos dolor harum provident et dicta. Nobis ut excepturi unde quia minima ut autem. Animi sunt perspiciatis perferendis et.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('26', 'Rowe Inc', '4', '1', '13694 Fay Tunnel Suite 154\nNew Norris, WI 77377', '2', 'Dignissimos optio id expedita earum. Corrupti neque qui eius. Ab molestiae aperiam qui quia rerum voluptas.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('27', 'Fritsch-Baumbach', '8', '1', '416 Ferry Loop\nLake Nettie, UT 61694-9320', '5', 'Labore ut cum velit optio quis. Laudantium tenetur voluptas et voluptate sint labore. Ea iusto fugiat quis delectus vel. Provident a aut tempore.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('28', 'Ullrich-Moen', '9', '1', '635 Maggio Locks Apt. 166\nNorth Dovieport, ID 49539', '1', 'Voluptatum voluptatem maxime sit ad ut. Aut est totam qui illo at omnis. Et ut voluptatibus distinctio mollitia architecto quia. Quaerat consequuntur exercitationem illo repellendus voluptatem modi qui.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('29', 'Schulist-Rohan', '1', '10', '65392 Jaskolski Mews Suite 976\nWest Rod, WV 53342-6898', '5', 'Libero sed aut sunt ullam provident. Maxime facilis nostrum dolor nobis nihil sed. Cupiditate iste voluptatum saepe. Ut voluptates facere et quibusdam sed.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('30', 'Jones-Parisian', '6', '10', '8458 Jenkins Ford\nZulaufview, DC 70998', '2', 'Error quidem impedit excepturi quisquam reprehenderit sapiente rerum repudiandae. Aut aut id et ipsa. Totam corrupti et harum ad.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('31', 'Pfeffer-Hackett', '2', '3', '343 Douglas Knoll Apt. 725\nNew Mafalda, NJ 88428-1804', '1', 'Officia id ab libero iste quam aliquam hic. Tempora omnis architecto incidunt ex. Dicta voluptas quia hic est. Cumque sed sed magni.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('32', 'Wintheiser and Sons', '1', '4', '72018 Jedediah Gateway\nCarterborough, AZ 65704-6530', '3', 'Sit dolore asperiores praesentium vel ab id. Cum sapiente qui occaecati eligendi impedit ea. Non perspiciatis rem inventore delectus et ipsam. Distinctio distinctio qui perspiciatis neque culpa.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('33', 'Grant and Sons', '6', '5', '6061 Mohr Square Apt. 045\nBuckridgemouth, OH 53725', '5', 'Voluptas in dolorem et corrupti eos. Fuga consequuntur cum quo voluptatem iusto officia fuga. Velit repudiandae vel quo. Voluptas eos voluptas quia consectetur qui.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('34', 'Kohler, Labadie and Johnson', '5', '11', '60059 Mable Way Suite 648\nMelanymouth, PA 79507', '5', 'Quo ratione ducimus velit rerum id. Quaerat eum ipsa autem maiores aut aut deleniti. Nam magnam dolor voluptatem ipsam. Ad et et non id hic optio.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('35', 'Dickens-Labadie', '2', '6', '7669 Sid Knolls\nStrackefurt, WI 11582-2060', '4', 'Aperiam minima autem rerum ducimus et dolores ut. Esse hic ab eligendi libero quia quod eaque. Vel earum commodi sunt voluptas. Vitae quia in provident quia.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('36', 'Nitzsche-Heathcote', '4', '9', '8312 Christelle Landing Apt. 437\nFaheymouth, MN 09619', '4', 'Voluptatem molestiae aut reiciendis eos quam tempore. Eligendi inventore eaque pariatur eaque quis perspiciatis quisquam necessitatibus. Reiciendis minima ut fuga cum quis. Animi et quia suscipit vitae est optio cum. Itaque pariatur sed minima unde.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('37', 'Durgan, Bailey and Armstrong', '6', '9', '023 Pedro Bridge\nWunschburgh, ND 18570', '4', 'Architecto voluptatibus est sed debitis temporibus eaque. Ut illum quisquam quis in voluptas veritatis.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('38', 'Runte-Upton', '8', '11', '743 Narciso Passage\nNorth Hankton, OK 40522-5186', '3', 'Soluta laboriosam vero eveniet. Ad quae ea molestiae fugiat. Nobis aperiam eius repudiandae qui earum reiciendis voluptatem tempore. Et quo cumque tempore mollitia quidem aut.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('39', 'Veum, Zemlak and Graham', '7', '6', '6840 Chesley Freeway\nCindyborough, OK 23716-9994', '4', 'Culpa incidunt dolor aut eius reprehenderit laboriosam in. Ullam quis dignissimos quia ea labore error aut. Veritatis ea numquam cupiditate sed numquam est.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('40', 'Hudson-Goyette', '7', '4', '96178 Lawrence River\nEmelieview, AR 61513', '5', 'Harum est ipsa non ea. Omnis ut suscipit quia unde quod sed. Commodi ea nam ut et fugiat.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('41', 'Corkery-Kohler', '8', '7', '002 Toy Lake Apt. 758\nDessiefurt, ME 44264', '2', 'Accusantium est labore animi id necessitatibus. Et voluptas eos repudiandae culpa et. Aut minima necessitatibus sunt id. Ea illum totam facilis amet fuga eligendi sed incidunt.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('42', 'Carroll and Sons', '6', '8', '7824 Wyman Oval Suite 030\nGusikowskiport, DE 91243', '1', 'Eius occaecati doloribus veritatis laboriosam. Doloribus maiores est ut soluta excepturi ipsa. Consequatur in veritatis et unde.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('43', 'Harvey, Halvorson and Schumm', '1', '3', '74774 Marianna Squares Suite 661\nDeckowside, GA 09922-9153', '2', 'Cum nostrum laborum molestiae velit. Ipsam iusto aut quo vero aut. Incidunt asperiores non voluptates sint in.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('44', 'Hilpert-Crona', '5', '9', '444 Jacobs Points Apt. 407\nLake Ward, NM 28179', '3', 'Et rerum ut deserunt quas quod repudiandae et nostrum. Vel impedit voluptates sint iure. Nobis inventore sed eos. Mollitia qui ea beatae earum aliquid.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('45', 'Jaskolski-Lowe', '1', '6', '319 Daniel Dale Apt. 726\nNorth June, MO 10435', '2', 'At minus ex ea numquam non laudantium deleniti. Provident perspiciatis et accusamus non dolor. Iusto earum aut aperiam voluptatum deleniti deserunt eligendi voluptatem. Voluptatem id consectetur cupiditate ex.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('46', 'Walter Ltd', '6', '10', '32349 Kamron Avenue Apt. 521\nSouth Kileyfurt, HI 10083', '1', 'Illum doloremque dolore maxime ut. Similique suscipit et perspiciatis quod earum et harum ad.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('47', 'McCullough Ltd', '10', '1', '336 Turner Corner\nGleichnerside, IA 74837', '1', 'Facere quia et nihil sed. Dolorem fugiat id et ex odit repellat id. Numquam laborum fugit autem iusto. Eaque quia voluptas odio vel sit labore.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('48', 'Sawayn Ltd', '3', '4', '119 Idella Mountain\nSouth Maximeburgh, PA 84904', '1', 'Rerum fugit aperiam odio perspiciatis omnis. Error vel eum facilis in totam. Atque omnis nihil repellat non dolorum. Iure aut dolorem sed dolore deleniti delectus.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('49', 'Bode, Wiegand and Brown', '6', '6', '9029 Jada Stream Suite 004\nLaurelview, HI 91409', '5', 'Voluptas in consequatur architecto qui. Velit est id et iusto quis sed eum. At itaque et nam in error debitis. Dolorem aliquam ea natus qui.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('50', 'Wilkinson, Predovic and Green', '5', '8', '76880 Emmanuel Loaf\nSchaeferborough, LA 54015-9734', '2', 'Voluptatum nihil iste ut aut. Quasi sunt molestias qui ea sit. Aut consequatur dicta sed cum odio ipsum assumenda odit. Tempore qui sed perferendis dolores optio nulla in quam.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('51', 'Rice, Hammes and Wyman', '10', '5', '519 Mayer Causeway Suite 316\nWilfredoton, OH 35840-7230', '3', 'Natus beatae voluptas provident illum aut architecto. Sit accusamus magnam ut et omnis. Similique esse dolorem harum quod incidunt nesciunt.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('52', 'Labadie-Schumm', '2', '9', '629 Lorenzo Landing Suite 043\nVeumton, VA 18571', '1', 'Vel et quia nostrum itaque quaerat quis temporibus. In qui et ab nostrum quaerat. Aspernatur a est quibusdam dolores.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('53', 'Hirthe-Considine', '6', '10', '77749 Balistreri Cove Suite 594\nNew Arne, NC 64245-7309', '4', 'Ut ut aspernatur dolorem iusto quidem debitis. Laudantium autem a deserunt aut adipisci. Quia est sed corporis quia et laudantium quos. Perspiciatis cupiditate similique ut est dolorum aliquam.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('54', 'Heidenreich Inc', '2', '5', '399 Rau Pike\nSouth Susanashire, NM 76389', '4', 'Vero enim amet illum. Nisi iusto voluptate consequatur officiis accusantium aperiam. Dolorem expedita sapiente enim aut sequi. Facilis facere consequatur et suscipit.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('55', 'Schowalter, Stokes and Cole', '8', '9', '1004 Wilburn Fields\nSouth Jo, AR 98343-4586', '3', 'Consequuntur magnam labore perspiciatis debitis. Quod accusantium corporis enim. Non nisi expedita quisquam sit.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('56', 'Will-Windler', '7', '11', '715 Hickle Village Apt. 772\nReingerside, ID 47323', '5', 'Dolorum minus explicabo quia sed rerum neque. Omnis ea tenetur et delectus. Similique dicta similique commodi harum quae exercitationem distinctio aut.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('57', 'Russel-Wyman', '3', '2', '8811 Eichmann Landing\nWest Miracleside, KS 20660', '3', 'Optio ut quo ratione voluptas dignissimos vitae. Architecto deserunt optio iste rerum. Ad et quae autem autem labore alias porro eum. Et expedita enim possimus est minus voluptate ut et.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('58', 'Thompson, Huels and Schowalter', '2', '1', '5770 Stracke Circle\nEmardport, VT 55401-7095', '5', 'Voluptatem quae odio esse dolores dolor. Et voluptates dolores voluptatibus voluptas quo ut aut iste. Corrupti dignissimos quaerat nulla tenetur in deserunt. Fuga enim fuga doloremque laborum.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('59', 'Steuber-Upton', '6', '1', '2083 Marley Trail\nGarrickside, VT 21472', '4', 'Cupiditate repellat quis aut ipsa. Magnam id iure molestiae eos quisquam atque voluptates. Et dolore omnis fugiat veniam laborum reiciendis modi.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('60', 'Nitzsche-Swaniawski', '3', '5', '664 Anjali Ville Apt. 813\nWavafurt, OR 03773', '3', 'Tempore iure fugit quis quis facere. Architecto ad mollitia ipsum alias aut doloremque. Quod cumque iusto ipsa laboriosam esse nihil eos.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('61', 'Cormier-Zulauf', '2', '5', '73356 Berniece Spurs\nNew Freedahaven, KS 41226-4914', '5', 'Architecto dolores repellat laborum deserunt et. Totam voluptate voluptas tenetur omnis sed at praesentium. Facilis odio porro voluptatum vero eius repudiandae occaecati. Voluptas illo vel delectus debitis aut nihil.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('62', 'Weimann-Kihn', '5', '6', '983 Ruthie Ridges Suite 937\nLake Teresa, MI 30636-5332', '1', 'Sint sit deleniti fugit consequatur. Iusto eum repellat quaerat nam sit dolorum ut vero. In et qui aliquam.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('63', 'Pollich-Weissnat', '8', '7', '8554 Vincenza Prairie Apt. 150\nLake Astrid, SC 65906-5537', '1', 'Ipsa quas ut accusamus est assumenda omnis hic. Vel pariatur est nesciunt pariatur nisi. Quia architecto officia laudantium facilis expedita animi non.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('64', 'Waelchi, Bashirian and Hermiston', '2', '10', '94013 Bettie Falls Apt. 350\nPort Mortimerville, NH 01257-0591', '5', 'Voluptas expedita facilis nostrum. Non voluptatum quia saepe. Ad enim fugit temporibus dolore et labore commodi. Facere quae doloribus qui aut.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('65', 'Volkman, Vandervort and Wolf', '2', '3', '115 Lorenz Unions Apt. 348\nWaynehaven, RI 60423-2064', '3', 'Impedit sed voluptate quae nihil sint aut qui est. Dolorum modi maiores ea corrupti. Repellendus molestias quia voluptas quis illo dolore. Et nulla sint quia.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('66', 'Keeling LLC', '4', '10', '3797 Nicolas Forks Apt. 161\nDanielmouth, MD 30400-1039', '1', 'Ab et illo natus culpa inventore. Perspiciatis quas hic debitis itaque.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('67', 'McDermott PLC', '3', '5', '575 Runolfsson Crest\nNoreneborough, CT 14774', '4', 'At quisquam commodi voluptatem qui qui. Mollitia aliquam qui saepe sapiente. Consequatur fugiat quae atque dignissimos similique.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('68', 'Jaskolski-Effertz', '8', '8', '33897 Dixie Mission Suite 242\nWest Marta, HI 34663-4843', '3', 'Sed numquam quia officiis et. Ducimus qui ullam et eius qui blanditiis et. Molestiae quia autem voluptatem corrupti modi quas ab sit. Quaerat ea exercitationem adipisci ipsa blanditiis ut et.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('69', 'Gorczany Inc', '7', '4', '021 Harber Unions\nLaylamouth, IL 04624', '5', 'Inventore saepe repudiandae aut nihil voluptatum delectus. Aut nostrum delectus et. Deserunt ducimus molestiae dignissimos deserunt modi sint sit.');
INSERT INTO `hotels` (`id`, `name`, `ht_country_id`, `ht_city_id`, `address`, `number_of_stars`, `description`) VALUES ('70', 'Hamill-Rogahn', '1', '6', '936 Leonor Drives\nSouth Celia, OK 26789', '1', 'Itaque aliquid cumque aut rem reiciendis. Aut excepturi et id deserunt totam. Illum in facilis consectetur dolor illum aut.');

INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('1', 'Minima earum amet iusto minima.', '4', '9', 'Id aut esse assumenda placeat est sint sint. Non harum qui commodi consequuntur. Culpa est non minima et voluptas. Quo possimus ea expedita quae nam. Ducimus dolore nulla suscipit explicabo veritatis.', 'dormouse-write-that-down-the-king-in-a-frightened-tone-the-queen-of-hearts-were-seated-on-their-faces-and-the-white-rabbit-it-was-out-of-the-officers-but-the-tops-of-the-house-which-was', '2022-10-12 17:00:00', '2022-10-12 20:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('2', 'Saepe sit nemo neque amet animi dolor.', '10', '3', 'Et provident perspiciatis sit et aliquid enim. Architecto molestiae est aut non. Reiciendis delectus dolores eaque ut in nulla. Beatae nobis recusandae ad quibusdam cum sed et.', 'hatter-was-the-same-words-as-before-its-all-his-fancy-that-they-never-executes-nobody-you-know-please-maam-is-this-new-zealand-or-australia-and-she-tried-to-fancy-to-herself-what-such', '2022-11-12 17:00:00', '2022-11-12 20:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('3', 'Maxime totam ducimus voluptates fugit molestiae.', '10', '10', 'Corporis blanditiis aut non reprehenderit cum illum minima sit. Ut odio voluptatibus quidem ratione. Autem qui et architecto quidem consequuntur. Nam voluptatem nulla ut modi dicta.', 'dodo-could-not-help-thinking-there-must-be-more-to-be-a-letter-written-by-the-hand-it-hurried-off-without-waiting-for-turns-quarrelling-all-the-time-he-was-speaking-so-that-her-neck-from-being', '2022-12-12 17:00:00', '2022-12-12 20:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('4', 'Corporis fugiat voluptatem commodi sit reprehenderit.', '6', '8', 'Doloribus ad esse iure non aut sequi enim quas. Saepe et dolore placeat nostrum illo.', 'this-question-the-dodo-had-paused-as-if-it-began-ordering-people-about-like-that-he-got-behind-alice-as-he-could-go-alice-took-up-the-chimney-has-he-said-alice-indignantly-and-she-went-to', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('5', 'Laborum vel nam cum vitae soluta est.', '8', '7', 'Quaerat omnis placeat ut quae. Nihil architecto aperiam quam maxime vel dolor rem. Ut laborum saepe molestiae. Enim et maxime itaque in atque voluptatem. Eaque repellendus deserunt laborum nesciunt magnam quis qui sint.', 'alice-felt-dreadfully-puzzled-the-hatters-remark-seemed-to-be-a-queer-thing-to-be-done-i-wonder-alice-guessed-in-a-low-curtain-she-had-sat-down-again-very-sadly-and-quietly-and-looked-at', '2022-10-12 17:00:00', '2022-10-12 20:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('6', 'Dolores libero quasi voluptatem debitis natus.', '10', '7', 'Totam consequuntur praesentium dolorem nam beatae. Et voluptatem omnis mollitia perspiciatis. Hic voluptas autem omnis nam officia voluptatem ut.', 'mouse-replied-rather-impatiently-any-shrimp-could-have-been-was-not-even-room-for-you-and-no-one-could-possibly-hear-you-and-certainly-there-was-no-use-in-waiting-by-the-end-of-the-doors-of-the', '2022-12-12 17:00:00', '2022-12-12 20:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('7', 'Aliquid perferendis qui architecto qui ea facere harum.', '2', '9', 'Nihil soluta quod mollitia saepe assumenda laudantium. Neque non iste reiciendis veniam ut perspiciatis qui. Praesentium et nam totam et sit.', 'all-this-time-with-one-of-the-window-and-on-both-sides-of-it-so-after-hunting-all-about-for-it-he-was-in-confusion-getting-the-dormouse-denied-nothing-being-fast-asleep-after-that', '2022-12-12 11:00:00', '2022-12-12 15:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('8', 'Quo est distinctio est ut voluptates minus quos quia.', '3', '4', 'Doloribus et deserunt nam voluptate qui ad corporis. Quasi nulla non libero et distinctio aspernatur. Occaecati repellat autem quas non est.', 'alice-who-was-passing-at-the-frontispiece-if-you-want-to-go-let-me-see-four-times-six-is-thirteen-and-four-times-seven-is-oh-dear-i-shall-have-to-whisper-a-hint-to-time-and-round-the-court', '2022-12-12 13:00:00', '2022-12-12 17:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('9', 'Beatae error a sapiente sed tenetur reprehenderit et.', '6', '11', 'Non minima odit ab repudiandae quidem ad minima. Qui deserunt porro est. Consequatur rerum eos eum vel porro.', 'mind-now-the-poor-little-thing-grunted-in-reply-it-had-left-off-quarrelling-with-the-mouse-was-bristling-all-over-and-both-footmen-alice-noticed-had-powdered-hair-that-would-always-get-into', '2022-12-05 17:00:00', '2022-12-05 20:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('10', 'Eos voluptatem in molestias nihil deserunt consequatur nostrum.', '9', '4', 'Sunt ut nam sit temporibus. Dolor cupiditate quod pariatur quia ipsum. Quia maiores dolores molestias. Tempora distinctio fugit pariatur quis nesciunt architecto velit.', 'the-frog-footman-repeated-in-the-newspapers-at-the-door-pray-what-is-the-same-thing-said-the-duchess-and-the-moral-of-that-is-take-care-of-the-day-and-this-alice-would-not-open-any-of', '2022-12-25 17:00:00', '2022-12-25 20:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('11', 'Architecto qui amet optio asperiores eum.', '7', '8', 'Quam eligendi libero saepe distinctio nesciunt sit. Eos veritatis enim sunt porro. Libero aut animi quis tempore et quae.', 'alice-as-she-had-looked-under-it-and-burning-with-curiosity-she-ran-out-of-the-guinea-pigs-cheered-and-was-just-saying-to-herself-in-my-going-out-altogether-like-a-jack-in-the-box-and-up-i', '2022-11-16 17:00:00', '2022-11-16 20:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('12', 'Minus voluptatem qui et similique quam nihil eaque.', '2', '8', 'Aut omnis ipsum occaecati aut quisquam enim. Corrupti qui quia eum et nam. Dolor provident et similique expedita totam. Et in eum voluptas.', 'alice-they-all-spoke-at-once-she-found-this-a-very-short-time-the-queen-furiously-throwing-an-inkstand-at-the-white-rabbit-and-thats-why-pig-she-said-it-to-her-usual-height-it-was-as-much', '2022-12-14 17:00:00', '2022-12-14 20:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('13', 'Voluptas rerum animi laborum aliquam voluptas ut.', '6', '2', 'Ipsum fuga dolorum ut error similique. Laudantium eveniet molestiae sunt quas quia rerum. Soluta dolores dicta eos eius dignissimos.', 'king-and-the-gryphon-repeated-impatiently-it-begins-i-passed-by-his-garden-and-i-had-our-dinah-here-i-know-who-i-am-but-id-better-take-him-his-fan-and-the-white-rabbit-jumping-up-and-beg-for', '2022-12-13 17:00:00', '2022-12-13 20:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('14', 'Et ducimus unde quaerat aliquid sint quidem quis.', '4', '10', 'Dicta cumque totam quibusdam libero quod soluta voluptate. Qui qui et ut ut modi. Iste quia dolorem porro perspiciatis sed minus. Consequatur voluptas praesentium et et sint ipsam.', 'alice-angrily-it-wasnt-very-civil-of-you-to-offer-it-said-the-gryphon-its-all-his-fancy-that-he-hasnt-got-no-business-of-mine-the-queen-turned-crimson-with-fury-and-after-folding-his', '2022-12-11 17:00:00', '2022-12-11 20:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('15', 'Laboriosam et inventore quos inventore impedit et dolor repudiandae.', '7', '8', 'Ut hic qui voluptatum velit. Rerum vero quaerat sunt officiis distinctio facilis. In amet quo harum atque ipsam iste qui. Molestiae quis nihil alias accusantium.', 'for-this-must-be-the-best-of-educations-in-fact-we-went-to-school-in-the-trial-done-she-thought-and-rightly-too-that-very-few-things-indeed-were-really-impossible-there-seemed-to-alice-with', '2022-12-10 17:00:00', '2022-12-10 20:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('16', 'Delectus vel sed et dignissimos.', '4', '10', 'Voluptatem dolorem dolore quis ut et. Aut quo neque cumque vero itaque voluptatem. Rerum maiores est at rem sed eligendi itaque ut. Incidunt dolores dolores cumque nostrum vel cumque eveniet.', 'dont-be-all-day-to-day-this-was-not-a-moment-like-a-frog-and-both-creatures-hid-their-faces-in-their-proper-places-all-he-repeated-with-great-emphasis-looking-hard-at-alice-the-moment-how', '2022-12-09 17:00:00', '2022-12-09 20:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('17', 'Suscipit beatae saepe commodi ab sunt.', '10', '5', 'Odit est ipsum quis doloremque. Laborum et soluta tempora debitis neque ea deleniti. Mollitia veritatis voluptas tempora autem dolorum.', 'caterpillar-took-the-hookah-into-its-mouth-again-and-did-not-wish-to-offend-the-dormouse-crossed-the-court-arm-in-arm-with-the-day-and-night-you-see-the-mock-turtle-in-a-whisper-that-would-be', '2022-12-08 17:00:00', '2022-12-08 20:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('18', 'Autem accusamus deserunt quia aut.', '5', '6', 'Ea iure a eum reprehenderit. Quibusdam sapiente cumque sapiente cum. Consequatur hic et et.', 'the-question-is-what-the-great-question-is-what-the-great-question-certainly-was-what-alice-looked-round-eager-to-see-the-queen-you-make-me-larger-it-must-be-shutting-up-like-a', '2022-12-07 17:00:00', '2022-12-07 20:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('19', 'Vero dolores repellendus minus distinctio dicta eos.', '8', '9', 'Quae architecto aut labore et cum non. Debitis placeat est sit consequatur explicabo. Minima cum accusamus cum qui sint quaerat. Qui sint dicta fuga magni saepe.', 'queen-shrieked-out-behead-that-dormouse-turn-that-dormouse-out-of-sight-then-it-watched-the-queen-shouted-at-the-end-if-you-didnt-like-cats-not-like-cats-cried-the-gryphon-you', '2022-12-06 17:00:00', '2022-12-06 20:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('20', 'Voluptate consectetur a voluptatem sunt.', '9', '4', 'Aliquam et molestiae laborum repellat voluptatum amet esse blanditiis. Quidem qui quasi et rem cum est. Molestias dolorem pariatur voluptatum harum et quos. Natus ut et non non nemo sint. Hic a iste quia qui.', 'you-gave-us-three-or-more-they-all-sat-down-with-wonder-at-the-footmans-head-it-just-missed-her-alice-caught-the-flamingo-and-brought-it-back-the-fight-was-over-and-both-the-hedgehogs-were-out', '2022-10-05 17:00:00', '2022-10-05 20:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('21', 'Qui amet blanditiis sapiente qui sequi.', '6', '7', 'Culpa quidem minima dignissimos qui. Fugiat aut ullam qui aut magnam sunt. Aperiam non error amet beatae quia.', 'five-i-heard-every-word-you-fellows-were-saying-tell-us-a-story-im-afraid-ive-offended-it-again-for-the-mouse-heard-this-it-turned-a-corner-oh-my-ears-and-whiskers-how-late-its', '2022-12-04 17:00:00', '2022-12-05 20:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('22', 'Inventore qui voluptatem aut aut occaecati qui incidunt.', '3', '10', 'Dolor quasi nesciunt fuga nam. Ipsa ut quod modi rerum eius quis eos. Dolore quae consequuntur sit doloremque. Amet amet est quis incidunt.', 'cat-went-on-i-must-go-by-the-whole-court-was-in-the-other-in-the-very-tones-of-her-ever-getting-out-of-sight-he-said-to-the-little-creature-down-and-felt-quite-relieved-to-see-what-the-name-of', '2022-12-03 17:00:00', '2022-12-03 20:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('23', 'Sed est eos eos earum nemo.', '5', '9', 'Omnis alias quia eligendi architecto dolor. Quo sed consectetur non animi nesciunt id. Corrupti explicabo accusamus necessitatibus vel ratione non aperiam. Sed ut reprehenderit fugit suscipit excepturi quae aut.', 'it-was-the-rabbit-came-near-her-about-four-feet-high-whoever-lives-there-thought-alice-as-all-the-creatures-order-one-about-and-called-out-first-witness-the-first-question-of-course-had', '2022-12-03 17:00:00', '2022-12-03 20:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('24', 'Commodi velit est qui fuga nulla quae.', '3', '7', 'Fuga dolor odio qui est fugit vero excepturi. Et illum aut et sapiente. Explicabo nam inventore et excepturi sed rerum maxime labore. Sint vitae eum quidem explicabo quaerat.', 'alices-first-thought-was-that-she-had-grown-to-her-feet-in-a-pleased-tone-pray-dont-trouble-yourself-to-say-anything-why-said-the-pigeon-in-a-bit-perhaps-it-hasnt-one-alice-ventured-to', '2022-12-02 17:00:00', '2022-12-02 20:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('25', 'Facilis consequatur minima et corrupti explicabo.', '8', '7', 'Non commodi ut sed vel iste quia minus. Ab quam qui dolore dolores magni et totam. Ullam ullam quae sed voluptas nobis consectetur. Et consequatur iste dolores dicta laboriosam velit et.', 'alice-or-perhaps-they-wont-walk-the-way-wherever-she-wanted-much-to-know-but-the-three-gardeners-who-were-giving-it-something-out-of-its-voice-back-to-land-again-and-did-not-notice-this', '2022-12-01 17:00:00', '2022-12-01 20:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('26', 'Aperiam voluptatem et ut est pariatur ut earum.', '7', '5', 'Quia id nulla et distinctio. Repellat mollitia sed aut quis in. Maiores est laboriosam vitae ea. Nihil et rem et fugit.', 'in-another-minute-the-whole-party-swam-to-the-rose-tree-she-went-on-saying-to-herself-suppose-it-should-be-free-of-them-bowed-low-would-you-tell-me-said-alice-a-little-startled-when-she', '2022-12-12 08:00:00', '2022-12-12 14:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('27', 'Facilis consequatur hic molestiae officia dolores.', '8', '7', 'Ullam odit dolorem accusantium inventore voluptatem illo error. Corrupti fuga consequatur necessitatibus ut illum vitae rerum explicabo. Corporis quos fugit dolor tenetur.', 'however-everything-is-to-day-and-yesterday-things-went-on-again-you-may-go-said-the-gryphon-and-it-said-in-a-low-voice-why-the-fact-is-you-are-a-simpleton-alice-did-not-answer-so', '2022-12-12 09:00:00', '2022-12-12 13:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('28', 'Occaecati dolor dolorem corporis quod.', '3', '9', 'Optio ut est dolor dolorem. Sequi aut animi doloremque in. Officiis est eum possimus ullam est nesciunt. Aut quo et minus. Aut molestias sed et et architecto.', 'and-beat-him-when-he-pleases-chorus-wow-wow-wow-here-you-may-sit-down-the-king-replied-here-the-dormouse-sulkily-remarked-if-you-please-sir-the-rabbit-started-violently-dropped', '2022-12-12 10:00:00', '2022-12-12 16:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('29', 'Autem iusto excepturi ratione.', '4', '3', 'Sint quia explicabo excepturi et recusandae voluptatem. Sit in illo amet officiis libero dolorem. Blanditiis sed modi eligendi asperiores in. Quis soluta quia harum molestiae.', 'hatter-said-turning-to-the-three-were-all-locked-and-when-alice-had-not-as-yet-had-any-sense-theyd-take-the-place-of-the-jury-consider-their-verdict-the-king-said-for-about-the-crumbs-said', '2022-12-12 17:00:00', '2022-12-12 20:00:00');
INSERT INTO `excursions` (`id`, `name`, `ex_country_id`, `ex_city_id`, `description`, `rout`, `begin_at`, `finish_at`) VALUES ('30', 'Nulla est ad perspiciatis.', '5', '5', 'Dolorem maiores quia enim voluptatem. Eum dolores impedit perferendis animi sed voluptatem. Non et ut in ipsum. Illo sapiente eum aliquam est impedit et.', 'i-ah-thats-the-great-concert-given-by-the-carrier-she-thought-and-how-funny-itll-seem-to-come-down-the-chimney-and-said-what-else-had-you-to-death-you-are-all-dry-he-is-gay-as-a-boon', '2022-12-12 17:00:00', '2022-12-12 21:00:00');

INSERT INTO flights VALUES
	('SU 5234', 'Moscow', 'Rome', '2022-10-05 12:00:00', '2022-10-05 15:00:00'),
	('FV 3655', 'Moscow', 'Stockholm', '2022-11-05 12:00:00', '2022-11-05 15:00:00'),
	('FW 5789', 'Saint-Petersburg', 'Stockholm', '2022-11-30 12:00:00', '2022-11-30 13:00:00'),
	('YR 4588', 'Saint-Petersburg', 'Antalia', '2022-11-02 00:00:00', '2022-11-03 05:00:00'),
	('JD 1247', 'Moscow', 'Warsaw', '2022-10-02 00:00:00', '2022-10-03 05:00:00'),
	('SW 2254', 'Moscow', 'Pekin', '2022-12-02 00:00:00', '2022-12-03 05:00:00'),
	('FD 4478', 'Saint-Petersburg', 'Sharm el-sheikh', '2022-10-13 12:00:00', '2022-10-13 15:00:00'),
	('SW 4579', 'Saint-Petersburg', 'Venice', '2022-10-13 12:00:00', '2022-10-13 16:00:00'),
	('FV 2355', 'Moscow', 'Hurghada', '2022-10-15 12:00:00', '2022-10-15 16:00:00'),
	('SU 9866', 'Moscow', 'Warsaw', '2022-10-23 12:00:00', '2022-10-23 16:00:00'),
	('FG 3365', 'Moscow', 'Rome', '2022-10-24 12:00:00', '2022-10-24 16:00:00');
	
INSERT INTO `catalog` (`id`, `name_of_tour`, `country_id`, `city_id`, `hotel_id`, `description`, `flight`, `excursion_includ_id`, `price`, `currency_des`, `begin_at`, `finish_at`) VALUES ('1', 'Repudiandae consequatur voluptatum at et odit dicta voluptate.', '7', '5', '41', 'Harum et ratione molestias ratione autem. Ducimus ea voluptas aut voluptas. Quos ipsam voluptatem sit facilis mollitia. Rerum veniam magni soluta maiores non non ab.', 'FD 4478', '13', '2441.94', 'USD', '2022-10-13', '2022-10-27');
INSERT INTO `catalog` (`id`, `name_of_tour`, `country_id`, `city_id`, `hotel_id`, `description`, `flight`, `excursion_includ_id`, `price`, `currency_des`, `begin_at`, `finish_at`) VALUES ('2', 'Exercitationem quisquam eius ipsa.', '1', '2', '26', 'Beatae enim est qui est ut. Tempora et explicabo impedit atque aspernatur eius distinctio libero. Quia laboriosam ab et.', NULL, '19', '3385.94', 'RUR', '2022-10-06', '2022-10-06');
INSERT INTO `catalog` (`id`, `name_of_tour`, `country_id`, `city_id`, `hotel_id`, `description`, `flight`, `excursion_includ_id`, `price`, `currency_des`, `begin_at`, `finish_at`) VALUES ('3', 'Quia ipsum et nobis quibusdam.', '2', '4', '27', 'Quibusdam reprehenderit praesentium ut necessitatibus. Minima et velit distinctio optio voluptas.', 'FG 3365', '7', '3301.83', 'EUR', '2022-10-24', '2022-11-07');
INSERT INTO `catalog` (`id`, `name_of_tour`, `country_id`, `city_id`, `hotel_id`, `description`, `flight`, `excursion_includ_id`, `price`, `currency_des`, `begin_at`, `finish_at`) VALUES ('4', 'Placeat veniam porro qui aut asperiores vel illo amet.', '6', '3', '2', 'Nostrum quos quo sunt et. Cum ad repudiandae in vero alias odit ut. Temporibus dolore voluptas fuga et impedit.', 'FW 5789', NULL, '505.47', 'USD', '2022-11-30', '2022-12-06');
INSERT INTO `catalog` (`id`, `name_of_tour`, `country_id`, `city_id`, `hotel_id`, `description`, `flight`, `excursion_includ_id`, `price`, `currency_des`, `begin_at`, `finish_at`) VALUES ('5', 'Ipsa est atque sit velit praesentium.', '9', '9', '65', 'Saepe tempora et ipsa aut vitae earum. Ipsam aspernatur omnis et enim atque modi. Quos quam consequuntur adipisci a dolores qui impedit.', 'SW 2254', '26', '3125.16', 'USD', '2022-12-02', '2022-12-12');
INSERT INTO `catalog` (`id`, `name_of_tour`, `country_id`, `city_id`, `hotel_id`, `description`, `flight`, `excursion_includ_id`, `price`, `currency_des`, `begin_at`, `finish_at`) VALUES ('6', 'In aut maiores ducimus aperiam et est.', '8', '10', '9', 'Beatae non alias error maiores quasi placeat voluptatem. Rem amet quia odit et sapiente itaque. Eos voluptatem nihil minus cupiditate.', NULL, '19', '2019.01', 'USD', '2022-12-05', '2022-12-15');
INSERT INTO `catalog` (`id`, `name_of_tour`, `country_id`, `city_id`, `hotel_id`, `description`, `flight`, `excursion_includ_id`, `price`, `currency_des`, `begin_at`, `finish_at`) VALUES ('7', 'Autem expedita est autem dolore consectetur dolores ad.', '8', '10', '33', 'Et molestiae harum consequuntur. Harum explicabo perspiciatis beatae reiciendis. Vel eius rerum veniam. Aut porro optio architecto iure.', NULL, NULL, '2896.54', 'USD', '2022-12-20', '2022-12-30');
INSERT INTO `catalog` (`id`, `name_of_tour`, `country_id`, `city_id`, `hotel_id`, `description`, `flight`, `excursion_includ_id`, `price`, `currency_des`, `begin_at`, `finish_at`) VALUES ('8', 'Beatae consequatur dicta aspernatur voluptate possimus natus.', '9', '9', '32', 'Nihil illum iste dolores modi. Consequatur et quibusdam ut veniam. Aut aliquid tempora magnam sit a id sed.', 'SW 2254', '18', '3534.6', 'USD', '2022-12-02', '2022-12-13');
INSERT INTO `catalog` (`id`, `name_of_tour`, `country_id`, `city_id`, `hotel_id`, `description`, `flight`, `excursion_includ_id`, `price`, `currency_des`, `begin_at`, `finish_at`) VALUES ('9', 'Id corrupti quae ducimus corporis nemo.', '6', '3', '40', 'Aut adipisci beatae odio aut beatae quod. Tenetur possimus asperiores optio culpa. Numquam voluptatem laborum dolor id quisquam omnis dolor laboriosam.', 'FW 5789', '10', '4997.66', 'USD', '2022-11-30', '2022-12-15');
INSERT INTO `catalog` (`id`, `name_of_tour`, `country_id`, `city_id`, `hotel_id`, `description`, `flight`, `excursion_includ_id`, `price`, `currency_des`, `begin_at`, `finish_at`) VALUES ('10', 'Voluptas cumque aut ipsa sunt quos.', '5', '8', '55', 'Ipsum possimus unde distinctio. Est aut dolor aut repellat temporibus maiores sit. Impedit dolorum accusantium accusantium.', 'YR 4588', '23', '4064.36', 'USD', '2022-11-02', '2022-11-14');
INSERT INTO `catalog` (`id`, `name_of_tour`, `country_id`, `city_id`, `hotel_id`, `description`, `flight`, `excursion_includ_id`, `price`, `currency_des`, `begin_at`, `finish_at`) VALUES ('11', 'Et voluptas tenetur aspernatur provident consequatur quam.', '3', '11', '12', 'Sunt amet accusamus ea delectus consectetur. Sed dolore officiis nemo aut. Dolorem eum odit suscipit minus dignissimos corrupti rem. Soluta harum quas iste officia corrupti quam ratione qui. Id voluptate odit reprehenderit dignissimos.', 'JD 1247', '30', '1256.43', 'EUR', '2022-10-02', '2022-10-07');

INSERT INTO applications (client_id, tour_id, `status`) VALUES
	(12, 6, 'created'),
	(65, 2, 'confirmed'),
	(58, 1, 'paid_for'),
	(1, 11, 'paid_for'),
	(6, 3, 'confirmed'),
	(79, 10, 'confirmed'),
	(42, 8, 'confirmed'),
	(3, 9, 'confirmed'),
	(36, 7, 'created'),
	(24, 4, 'created'),
	(99, 5, 'paid_for'),
	(85, 2, 'paid_for'),
	(13, 4, 'paid_for'),
	(63, 5, 'paid_for'),
	(59, 11, 'confirmed'),
	(50, 10, 'confirmed'),
	(47, 9, 'confirmed'),
	(5, 3, 'confirmed'),
	(92, 7, 'confirmed'),
	(33, 6, 'paid_for');
	